local set = vim.opt

set.undofile = true
set.undolevels=5000
set.number = true
set.relativenumber = true
set.mouse = 'a'
set.scrolloff = 12
set.whichwrap = 'h,l'
set.ignorecase = true
set.smartcase = true
set.expandtab = true
set.tabstop = 4
set.shiftwidth = 4
set.softtabstop = 4
set.wildignorecase = true
set.wildignore = '*.png,*.jpg,*.gif'
set.splitbelow = true
set.splitright = true
set.termguicolors = true
